import { type Dictionary, t } from "intlayer";

const commonContent = {
	key: "common",
	content: {
		navigation: {
			home: t({
				en: "Home",
				zh: "首页",
				ja: "ホーム",
				ko: "홈",
				fr: "Accueil",
				de: "Startseite",
				es: "Inicio",
			}),
			posts: t({
				en: "Posts",
				zh: "文章",
				ja: "記事",
				ko: "게시물",
				fr: "Articles",
				de: "Beiträge",
				es: "Publicaciones",
			}),
			products: t({
				en: "Products",
				zh: "产品",
				ja: "製品",
				ko: "제품",
				fr: "Produits",
				de: "Produkte",
				es: "Productos",
			}),
		},
		actions: {
			viewAll: t({
				en: "View All",
				zh: "查看全部",
				ja: "すべて見る",
				ko: "모두 보기",
				fr: "Voir tout",
				de: "Alle anzeigen",
				es: "Ver todo",
			}),
			readMore: t({
				en: "Read More",
				zh: "阅读更多",
				ja: "続きを読む",
				ko: "더 읽기",
				fr: "Lire la suite",
				de: "Mehr lesen",
				es: "Leer más",
			}),
			readPosts: t({
				en: "Read Posts",
				zh: "阅读文章",
				ja: "記事を読む",
				ko: "게시물 읽기",
				fr: "Lire les articles",
				de: "Beiträge lesen",
				es: "Leer publicaciones",
			}),
			viewProducts: t({
				en: "View Products",
				zh: "查看产品",
				ja: "製品を見る",
				ko: "제품 보기",
				fr: "Voir les produits",
				de: "Produkte ansehen",
				es: "Ver productos",
			}),
		},
		language: {
			switchLanguage: t({
				en: "Language",
				zh: "语言",
				ja: "言語",
				ko: "언어",
				fr: "Langue",
				de: "Sprache",
				es: "Idioma",
			}),
		},
		// Homepage
		homepage: {
			badge: t({
				en: "New Experience",
				zh: "全新体验",
				ja: "新体験",
				ko: "새로운 경험",
				fr: "Nouvelle expérience",
				de: "Neue Erfahrung",
				es: "Nueva experiencia",
			}),
			title: t({
				en: "Modern Headless CMS.",
				zh: "现代无头 CMS。",
				ja: "モダンヘッドレスCMS。",
				ko: "모던 헤드리스 CMS.",
				fr: "CMS Headless Moderne.",
				de: "Modernes Headless CMS.",
				es: "CMS Headless Moderno.",
			}),
			subtitle: t({
				en: "Explore the latest insights and products delivered through a cutting-edge headless WordPress architecture.",
				zh: "探索通过前沿无头 WordPress 架构提供的最新见解和产品。",
				ja: "最先端のヘッドレスWordPressアーキテクチャで提供される最新の情報と製品をご覧ください。",
				ko: "최첨단 헤드리스 WordPress 아키텍처를 통해 제공되는 최신 인사이트와 제품을 살펴보세요.",
				fr: "Découvrez les dernières informations et produits fournis via une architecture WordPress headless de pointe.",
				de: "Entdecken Sie die neuesten Einblicke und Produkte, bereitgestellt durch eine hochmoderne Headless-WordPress-Architektur.",
				es: "Explore las últimas perspectivas y productos entregados a través de una arquitectura WordPress headless de vanguardia.",
			}),
		},
		// Sections
		sections: {
			articles: {
				title: t({
					en: "Articles",
					zh: "文章",
					ja: "記事",
					ko: "게시물",
					fr: "Articles",
					de: "Artikel",
					es: "Artículos",
				}),
				subtitle: t({
					en: "Latest news and deep insights",
					zh: "最新新闻和深度见解",
					ja: "最新ニュースと深い洞察",
					ko: "최신 뉴스와 깊은 통찰력",
					fr: "Dernières nouvelles et analyses approfondies",
					de: "Neueste Nachrichten und tiefe Einblicke",
					es: "Últimas noticias y perspectivas profundas",
				}),
				badge: t({
					en: "Insights",
					zh: "洞察",
					ja: "インサイト",
					ko: "인사이트",
					fr: "Perspectives",
					de: "Einblicke",
					es: "Perspectivas",
				}),
				pageSubtitle: t({
					en: "Discover ideas and insights, explore our latest published articles.",
					zh: "发现想法和见解，探索我们最新发布的文章。",
					ja: "アイデアと洞察を発見し、最新の公開記事をご覧ください。",
					ko: "아이디어와 통찰력을 발견하고 최신 게시물을 살펴보세요.",
					fr: "Découvrez des idées et des perspectives, explorez nos derniers articles publiés.",
					de: "Entdecken Sie Ideen und Einblicke, erkunden Sie unsere neuesten veröffentlichten Artikel.",
					es: "Descubre ideas y perspectivas, explora nuestros últimos artículos publicados.",
				}),
				empty: t({
					en: "No articles found",
					zh: "未找到文章",
					ja: "記事が見つかりません",
					ko: "게시물이 없습니다",
					fr: "Aucun article trouvé",
					de: "Keine Artikel gefunden",
					es: "No se encontraron artículos",
				}),
			},
			products: {
				title: t({
					en: "Products",
					zh: "产品",
					ja: "製品",
					ko: "제품",
					fr: "Produits",
					de: "Produkte",
					es: "Productos",
				}),
				subtitle: t({
					en: "Curated selection of quality items",
					zh: "精选优质商品",
					ja: "厳選された高品質アイテム",
					ko: "엄선된 품질 상품",
					fr: "Sélection de produits de qualité",
					de: "Kuratierte Auswahl hochwertiger Artikel",
					es: "Selección curada de artículos de calidad",
				}),
				badge: t({
					en: "Store",
					zh: "商店",
					ja: "ストア",
					ko: "스토어",
					fr: "Boutique",
					de: "Laden",
					es: "Tienda",
				}),
				pageSubtitle: t({
					en: "Curated selection of high-quality items to meet your diverse needs.",
					zh: "精选优质商品，满足您的多样化需求。",
					ja: "お客様の多様なニーズに応える厳選された高品質アイテム。",
					ko: "다양한 요구를 충족하는 엄선된 고품질 상품.",
					fr: "Sélection de produits de haute qualité pour répondre à vos besoins variés.",
					de: "Kuratierte Auswahl hochwertiger Artikel für Ihre vielfältigen Bedürfnisse.",
					es: "Selección curada de artículos de alta calidad para satisfacer sus diversas necesidades.",
				}),
				empty: t({
					en: "No products found",
					zh: "未找到产品",
					ja: "製品が見つかりません",
					ko: "제품이 없습니다",
					fr: "Aucun produit trouvé",
					de: "Keine Produkte gefunden",
					es: "No se encontraron productos",
				}),
			},
		},
		// Error states
		errors: {
			loadFailed: t({
				en: "Load Failed",
				zh: "加载失败",
				ja: "読み込み失敗",
				ko: "로드 실패",
				fr: "Échec du chargement",
				de: "Laden fehlgeschlagen",
				es: "Error al cargar",
			}),
			tryAgain: t({
				en: "Please refresh the page to try again",
				zh: "请刷新页面重试",
				ja: "ページを更新して再試行してください",
				ko: "페이지를 새로고침하여 다시 시도하세요",
				fr: "Veuillez actualiser la page pour réessayer",
				de: "Bitte aktualisieren Sie die Seite, um es erneut zu versuchen",
				es: "Por favor actualice la página para intentar de nuevo",
			}),
			notFound: {
				title: t({
					en: "Page not found",
					zh: "页面未找到",
					ja: "ページが見つかりません",
					ko: "페이지를 찾을 수 없습니다",
					fr: "Page non trouvée",
					de: "Seite nicht gefunden",
					es: "Página no encontrada",
				}),
				message: t({
					en: "The page you're looking for doesn't exist or has been moved.",
					zh: "您正在查找的页面不存在或已被移动。",
					ja: "お探しのページは存在しないか、移動されました。",
					ko: "찾으시는 페이지가 존재하지 않거나 이동되었습니다.",
					fr: "La page que vous recherchez n'existe pas ou a été déplacée.",
					de: "Die gesuchte Seite existiert nicht oder wurde verschoben.",
					es: "La página que busca no existe o ha sido movida.",
				}),
				backToHome: t({
					en: "Back to Home",
					zh: "返回首页",
					ja: "ホームに戻る",
					ko: "홈으로 돌아가기",
					fr: "Retour à l'accueil",
					de: "Zurück zur Startseite",
					es: "Volver al inicio",
				}),
				browseArticles: t({
					en: "Browse Articles",
					zh: "浏览文章",
					ja: "記事を見る",
					ko: "게시물 둘러보기",
					fr: "Parcourir les articles",
					de: "Artikel durchsuchen",
					es: "Explorar artículos",
				}),
			},
		},
	},
} satisfies Dictionary;

export default commonContent;
