/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ProductsIndexRouteImport } from './routes/{-$locale}/products/index'
import { Route as Char123LocaleChar125PostsIndexRouteImport } from './routes/{-$locale}/posts/index'
import { Route as Char123LocaleChar125ProductsProductIdRouteImport } from './routes/{-$locale}/products/$productId'
import { Route as Char123LocaleChar125PostsPostIdRouteImport } from './routes/{-$locale}/posts/$postId'
import { Route as ApiWebhookRevalidateRouteImport } from './routes/api/webhook/revalidate'
import { Route as ApiKvSyncRouteImport } from './routes/api/kv/sync'
import { Route as Char123LocaleChar125ProductsCategoriesIndexRouteImport } from './routes/{-$locale}/products/categories/index'
import { Route as Char123LocaleChar125PostsCategoriesIndexRouteImport } from './routes/{-$locale}/posts/categories/index'
import { Route as Char123LocaleChar125ProductsCategoriesCategorySlugRouteImport } from './routes/{-$locale}/products/categories/$categorySlug'
import { Route as Char123LocaleChar125PostsTagsTagSlugRouteImport } from './routes/{-$locale}/posts/tags/$tagSlug'
import { Route as Char123LocaleChar125PostsCategoriesCategorySlugRouteImport } from './routes/{-$locale}/posts/categories/$categorySlug'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProductsIndexRoute =
  Char123LocaleChar125ProductsIndexRouteImport.update({
    id: '/{-$locale}/products/',
    path: '/{-$locale}/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PostsIndexRoute =
  Char123LocaleChar125PostsIndexRouteImport.update({
    id: '/{-$locale}/posts/',
    path: '/{-$locale}/posts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProductsProductIdRoute =
  Char123LocaleChar125ProductsProductIdRouteImport.update({
    id: '/{-$locale}/products/$productId',
    path: '/{-$locale}/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PostsPostIdRoute =
  Char123LocaleChar125PostsPostIdRouteImport.update({
    id: '/{-$locale}/posts/$postId',
    path: '/{-$locale}/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhookRevalidateRoute = ApiWebhookRevalidateRouteImport.update({
  id: '/api/webhook/revalidate',
  path: '/api/webhook/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKvSyncRoute = ApiKvSyncRouteImport.update({
  id: '/api/kv/sync',
  path: '/api/kv/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125ProductsCategoriesIndexRoute =
  Char123LocaleChar125ProductsCategoriesIndexRouteImport.update({
    id: '/{-$locale}/products/categories/',
    path: '/{-$locale}/products/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PostsCategoriesIndexRoute =
  Char123LocaleChar125PostsCategoriesIndexRouteImport.update({
    id: '/{-$locale}/posts/categories/',
    path: '/{-$locale}/posts/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProductsCategoriesCategorySlugRoute =
  Char123LocaleChar125ProductsCategoriesCategorySlugRouteImport.update({
    id: '/{-$locale}/products/categories/$categorySlug',
    path: '/{-$locale}/products/categories/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PostsTagsTagSlugRoute =
  Char123LocaleChar125PostsTagsTagSlugRouteImport.update({
    id: '/{-$locale}/posts/tags/$tagSlug',
    path: '/{-$locale}/posts/tags/$tagSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PostsCategoriesCategorySlugRoute =
  Char123LocaleChar125PostsCategoriesCategorySlugRouteImport.update({
    id: '/{-$locale}/posts/categories/$categorySlug',
    path: '/{-$locale}/posts/categories/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/kv/sync': typeof ApiKvSyncRoute
  '/api/webhook/revalidate': typeof ApiWebhookRevalidateRoute
  '/{-$locale}/posts/$postId': typeof Char123LocaleChar125PostsPostIdRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/posts': typeof Char123LocaleChar125PostsIndexRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/posts/categories/$categorySlug': typeof Char123LocaleChar125PostsCategoriesCategorySlugRoute
  '/{-$locale}/posts/tags/$tagSlug': typeof Char123LocaleChar125PostsTagsTagSlugRoute
  '/{-$locale}/products/categories/$categorySlug': typeof Char123LocaleChar125ProductsCategoriesCategorySlugRoute
  '/{-$locale}/posts/categories': typeof Char123LocaleChar125PostsCategoriesIndexRoute
  '/{-$locale}/products/categories': typeof Char123LocaleChar125ProductsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/kv/sync': typeof ApiKvSyncRoute
  '/api/webhook/revalidate': typeof ApiWebhookRevalidateRoute
  '/{-$locale}/posts/$postId': typeof Char123LocaleChar125PostsPostIdRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/posts': typeof Char123LocaleChar125PostsIndexRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/posts/categories/$categorySlug': typeof Char123LocaleChar125PostsCategoriesCategorySlugRoute
  '/{-$locale}/posts/tags/$tagSlug': typeof Char123LocaleChar125PostsTagsTagSlugRoute
  '/{-$locale}/products/categories/$categorySlug': typeof Char123LocaleChar125ProductsCategoriesCategorySlugRoute
  '/{-$locale}/posts/categories': typeof Char123LocaleChar125PostsCategoriesIndexRoute
  '/{-$locale}/products/categories': typeof Char123LocaleChar125ProductsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/kv/sync': typeof ApiKvSyncRoute
  '/api/webhook/revalidate': typeof ApiWebhookRevalidateRoute
  '/{-$locale}/posts/$postId': typeof Char123LocaleChar125PostsPostIdRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/posts/': typeof Char123LocaleChar125PostsIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/posts/categories/$categorySlug': typeof Char123LocaleChar125PostsCategoriesCategorySlugRoute
  '/{-$locale}/posts/tags/$tagSlug': typeof Char123LocaleChar125PostsTagsTagSlugRoute
  '/{-$locale}/products/categories/$categorySlug': typeof Char123LocaleChar125ProductsCategoriesCategorySlugRoute
  '/{-$locale}/posts/categories/': typeof Char123LocaleChar125PostsCategoriesIndexRoute
  '/{-$locale}/products/categories/': typeof Char123LocaleChar125ProductsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/api/kv/sync'
    | '/api/webhook/revalidate'
    | '/{-$locale}/posts/$postId'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/posts'
    | '/{-$locale}/products'
    | '/{-$locale}/posts/categories/$categorySlug'
    | '/{-$locale}/posts/tags/$tagSlug'
    | '/{-$locale}/products/categories/$categorySlug'
    | '/{-$locale}/posts/categories'
    | '/{-$locale}/products/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/api/kv/sync'
    | '/api/webhook/revalidate'
    | '/{-$locale}/posts/$postId'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/posts'
    | '/{-$locale}/products'
    | '/{-$locale}/posts/categories/$categorySlug'
    | '/{-$locale}/posts/tags/$tagSlug'
    | '/{-$locale}/products/categories/$categorySlug'
    | '/{-$locale}/posts/categories'
    | '/{-$locale}/products/categories'
  id:
    | '__root__'
    | '/{-$locale}/'
    | '/api/kv/sync'
    | '/api/webhook/revalidate'
    | '/{-$locale}/posts/$postId'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/posts/'
    | '/{-$locale}/products/'
    | '/{-$locale}/posts/categories/$categorySlug'
    | '/{-$locale}/posts/tags/$tagSlug'
    | '/{-$locale}/products/categories/$categorySlug'
    | '/{-$locale}/posts/categories/'
    | '/{-$locale}/products/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  ApiKvSyncRoute: typeof ApiKvSyncRoute
  ApiWebhookRevalidateRoute: typeof ApiWebhookRevalidateRoute
  Char123LocaleChar125PostsPostIdRoute: typeof Char123LocaleChar125PostsPostIdRoute
  Char123LocaleChar125ProductsProductIdRoute: typeof Char123LocaleChar125ProductsProductIdRoute
  Char123LocaleChar125PostsIndexRoute: typeof Char123LocaleChar125PostsIndexRoute
  Char123LocaleChar125ProductsIndexRoute: typeof Char123LocaleChar125ProductsIndexRoute
  Char123LocaleChar125PostsCategoriesCategorySlugRoute: typeof Char123LocaleChar125PostsCategoriesCategorySlugRoute
  Char123LocaleChar125PostsTagsTagSlugRoute: typeof Char123LocaleChar125PostsTagsTagSlugRoute
  Char123LocaleChar125ProductsCategoriesCategorySlugRoute: typeof Char123LocaleChar125ProductsCategoriesCategorySlugRoute
  Char123LocaleChar125PostsCategoriesIndexRoute: typeof Char123LocaleChar125PostsCategoriesIndexRoute
  Char123LocaleChar125ProductsCategoriesIndexRoute: typeof Char123LocaleChar125ProductsCategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/products/': {
      id: '/{-$locale}/products/'
      path: '/{-$locale}/products'
      fullPath: '/{-$locale}/products'
      preLoaderRoute: typeof Char123LocaleChar125ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/posts/': {
      id: '/{-$locale}/posts/'
      path: '/{-$locale}/posts'
      fullPath: '/{-$locale}/posts'
      preLoaderRoute: typeof Char123LocaleChar125PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/products/$productId': {
      id: '/{-$locale}/products/$productId'
      path: '/{-$locale}/products/$productId'
      fullPath: '/{-$locale}/products/$productId'
      preLoaderRoute: typeof Char123LocaleChar125ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/posts/$postId': {
      id: '/{-$locale}/posts/$postId'
      path: '/{-$locale}/posts/$postId'
      fullPath: '/{-$locale}/posts/$postId'
      preLoaderRoute: typeof Char123LocaleChar125PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/revalidate': {
      id: '/api/webhook/revalidate'
      path: '/api/webhook/revalidate'
      fullPath: '/api/webhook/revalidate'
      preLoaderRoute: typeof ApiWebhookRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kv/sync': {
      id: '/api/kv/sync'
      path: '/api/kv/sync'
      fullPath: '/api/kv/sync'
      preLoaderRoute: typeof ApiKvSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/products/categories/': {
      id: '/{-$locale}/products/categories/'
      path: '/{-$locale}/products/categories'
      fullPath: '/{-$locale}/products/categories'
      preLoaderRoute: typeof Char123LocaleChar125ProductsCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/posts/categories/': {
      id: '/{-$locale}/posts/categories/'
      path: '/{-$locale}/posts/categories'
      fullPath: '/{-$locale}/posts/categories'
      preLoaderRoute: typeof Char123LocaleChar125PostsCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/products/categories/$categorySlug': {
      id: '/{-$locale}/products/categories/$categorySlug'
      path: '/{-$locale}/products/categories/$categorySlug'
      fullPath: '/{-$locale}/products/categories/$categorySlug'
      preLoaderRoute: typeof Char123LocaleChar125ProductsCategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/posts/tags/$tagSlug': {
      id: '/{-$locale}/posts/tags/$tagSlug'
      path: '/{-$locale}/posts/tags/$tagSlug'
      fullPath: '/{-$locale}/posts/tags/$tagSlug'
      preLoaderRoute: typeof Char123LocaleChar125PostsTagsTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/posts/categories/$categorySlug': {
      id: '/{-$locale}/posts/categories/$categorySlug'
      path: '/{-$locale}/posts/categories/$categorySlug'
      fullPath: '/{-$locale}/posts/categories/$categorySlug'
      preLoaderRoute: typeof Char123LocaleChar125PostsCategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  ApiKvSyncRoute: ApiKvSyncRoute,
  ApiWebhookRevalidateRoute: ApiWebhookRevalidateRoute,
  Char123LocaleChar125PostsPostIdRoute: Char123LocaleChar125PostsPostIdRoute,
  Char123LocaleChar125ProductsProductIdRoute:
    Char123LocaleChar125ProductsProductIdRoute,
  Char123LocaleChar125PostsIndexRoute: Char123LocaleChar125PostsIndexRoute,
  Char123LocaleChar125ProductsIndexRoute:
    Char123LocaleChar125ProductsIndexRoute,
  Char123LocaleChar125PostsCategoriesCategorySlugRoute:
    Char123LocaleChar125PostsCategoriesCategorySlugRoute,
  Char123LocaleChar125PostsTagsTagSlugRoute:
    Char123LocaleChar125PostsTagsTagSlugRoute,
  Char123LocaleChar125ProductsCategoriesCategorySlugRoute:
    Char123LocaleChar125ProductsCategoriesCategorySlugRoute,
  Char123LocaleChar125PostsCategoriesIndexRoute:
    Char123LocaleChar125PostsCategoriesIndexRoute,
  Char123LocaleChar125ProductsCategoriesIndexRoute:
    Char123LocaleChar125ProductsCategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
